### PR TITLE
0.6.1-alpha

### PR DESCRIPTION
**Pull request by Bistard**
## Summary by Sourcery

Introduce drag-and-drop functionality for editor blocks and enhance the input rule system. Add zoom controls for the application window and update Electron to version 25.0.0. Improve event handling and widget systems in the editor.

New Features:
- Introduce drag-and-drop functionality for editor blocks, allowing users to move blocks within the editor using a drag handle.
- Add support for zooming in and out of the application window, with keyboard shortcuts for quick access.
- Enable native title bar instead of drawing by ourselves in the renderer process.

Enhancements:
- Refactor the editor's input rule system to support more complex replacement strategies and conditions.
- Improve the editor's event handling by introducing a more comprehensive event broadcaster for mouse and drag events.
- Enhance the editor's widget system with a new block handle widget for better block manipulation.

Build:
- Update Electron to version 25.0.0 to leverage new features and improvements.

### CODE REVIEW

**Review by AAsteria — CHANGES_REQUESTED** [review]
1. [x] editor content responsiveness issue
2. [ ] collapsed outline not be able to expand again 
3. [ ] on a normal 16 inch laptop, the outline only shows when the size of the app window almost equal to full screen, which lowers user experience
4. [ ] when using ctrl/cmd to enlarge the content of the app, parts of the navigation panel contents should remain at a minimal size (this size should be larger than the minimal size of other components like the editor text size, the file tree content text size, etc.) which still support basic user interactions. Learn from VSCode.

**Comment by Bistard** [comment]
@sourcery-ai

**Comment by Bistard** [comment]
@AAsteria 明天我准备升级一个版本号，你可以在此之前简略地review一下~

**Review by AAsteria — APPROVED** [review]
Looks good ~ Approved!

**Pull request merged**
